# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="au915_1/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="au915_1/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="au915_1/gateway/{{ .GatewayID }}/command/#"

# Gateway backend configuration.
[backend]

# Backend type.
#
# Valid options are:
#   * semtech_udp
#   * concentratord
#   * basic_station
type="basic_station"

  # Basic Station backend.
  [backend.basic_station]

  # ip:port to bind the Websocket listener to.
  bind=":3001"

  # TLS certificate and key files.
  #
  # When set, the websocket listener will use TLS to secure the connections
  # between the gateways and ChirpStack Gateway Bridge (optional).
  #tls_cert="certs/chirpstack-gateway-bridge/basicstation/server/basicstation-server.pem"
  #tls_key="certs/chirpstack-gateway-bridge/basicstation/server/basicstation-server-key.pem"

  # TLS CA certificate.
  #
  # When configured, ChirpStack Gateway Bridge will validate that the client
  # certificate of the gateway has been signed by this CA certificate.
  ca_cert=""

  # Stats interval.
  #
  # This defines the interval in which the ChirpStack Gateway Bridge forwards
  # the uplink / downlink statistics.
  stats_interval="30s"

  # Ping interval.
  ping_interval="1m0s"

  # Timesync interval.
  #
  # This defines the interval in which the ChirpStack Gateway Bridge sends
  # a timesync request to the gateway. Setting this to 0 disables sending
  # timesync requests.
  timesync_interval="1h0m0s"

  # Read timeout.
  #
  # This interval must be greater than the configured ping interval.
  read_timeout="1m5s"

  # Write timeout.
  write_timeout="1s"

  # Region.
  #
  # Please refer to the LoRaWAN Regional Parameters specification
  # for the complete list of common region names.
  region="AU915"

  # Minimal frequency (Hz).
  frequency_min=916800000

  # Maximum frequency (Hz).
  frequency_max=927500000

  # Concentrator configuration.
  #
  # This section contains the configuration for the SX1301 concentrator chips.
  [[backend.basic_station.concentrators]]

    # Multi-SF channel configuration.
    [backend.basic_station.concentrators.multi_sf]

    # Frequencies (Hz).
    frequencies=[
      916800000,
      917200000,
      917200000,
      917400000,
      917600000,
      917800000,
      918000000,
      918200000,
    ]

    # LoRa STD channel.
    [backend.basic_station.concentrators.lora_std]

    # Frequency (Hz).
    frequency=917500000

    # Bandwidth (Hz).
    bandwidth=500000

    # Spreading factor.
    spreading_factor=8
